// Auto-generated by GitHub Actions — DO NOT edit manually.
// Exposes secrets as window globals so the browser can send Telegram alerts
// and push positions.json without storing credentials in localStorage.
window.__GH_PAT       = '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';
window.__GH_REPO      = 'ahsan520/alpha';
window.__TG_TOKEN     = '8486955329:AAFP7own5Ksijclb9VStLLW7EFyKWT873hk';
window.__TG_CHAT      = '7956749027';
